steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/documentation-tutor/simplifi-repo/simplifi-app:v0', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/documentation-tutor/simplifi-repo/simplifi-app:v0']

# Deploy container image to GKE
# - name: 'gcr.io/cloud-builders/gke-deploy'
#   args:
#   - run
#   - --filename=k8s/
#   - --location=us-east1
#   - --cluster=simplifi-cluster
#   - --image=us-east1-docker.pkg.dev/documentation-tutor/simplifi-repo/simplifi-app:v0

# substitutions:
#   _REGION: us-central1 # Default region
#   _CLUSTER_NAME: my-cluster # Default cluster name
#   _SERVICE_NAME: my-app # Default service name

# Store images in Artifact Registry
images:
  - 'us-east1-docker.pkg.dev/documentation-tutor/simplifi-repo/simplifi-app:v0'

# Optional timeout setting (in seconds)
timeout: '1800s'

options:
   logging: CLOUD_LOGGING_ONLY 