apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplifi-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simplifi-backend
  template:
    metadata:
      labels:
        app: simplifi-backend
    spec:
      containers:
      - name: simplifi-backend-container
        image: us-east1-docker.pkg.dev/documentation-tutor/simplifi-repo/simplifi-app:v0
        ports:
        - containerPort: 7860
        envFrom:
        - secretRef:
            name: simplifi-secrets
      volumes:
      - name: simplifi-secrets-volume
        csi:
          driver: secrets-store-gke.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: simplifi-secrets-provider