apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: simplifi-secrets-provider
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/953062027002/secrets/OPENAI_API_KEY/versions/1"
        path: "openai-api-key"
  secretObjects:
    - secretName: simplifi-secrets
      type: Opaque
      data:
        - objectName: "openai-api-key"
          key: OPENAI_API_KEY